application: smartninjaorg1
version: 1-57
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.app

inbound_services:
- mail

error_handlers:
- file: app/templates/404.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest